### ISSUE TITLE
Demo solution published to GitHub pages?

### ISSUE THREAD

**Issue by SimonDarksideJ** [echo3Dco/Unity-WebGL-echo3D-demo-Aquarium#1]
Would be better if the compiled solution was also published to GitHub pages so the example could be seen before cloning and deploying manually.

**Comment by echo3Dco** [comment]
That's a great suggestion, Simon! Our team will look into it.

**Comment by andres-echo** [comment]
Hi Simon, thanks again for the good idea. A build of the app can now be previewed here: https://echo3dco.github.io/Unity-WebGL-echo3D-demo-Aquarium/
